name: Deploy React Application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 0 * * 5' # each Friday, 12 AM

jobs:
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x] # We will deploy with only one version of node

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: create env file
        run: |
          touch .env
          echo GH_TOKEN=${{ secrets.GITHUB_TOKEN }} >> .env
      - name: yarn fetch
        run: |
          yarn install --frozen-lockfile --immutable --immutable-cache --check-cache
          CI='' yarn fetch # fetch all repos issues
      - name: persist issues
        run: |
          git add github_repositories.json
          git commit -m "auto: update issues"
          git push origin master

